name: Testing

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Run tests
        uses: docker://mileschou/phalcon:7.3-alpine
        run: |
          composer install --prefer-dist --no-progress --no-suggest
          composer run-script test
