name: Testing

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: docker://mileschou/phalcon:7.3-alpine

      - name: Validate composer.json and composer.lock
        run: php -m

#      - name: Install dependencies
#        run: composer install --prefer-dist --no-progress --no-suggest
#
#      - name: Run tests
#        run: composer run-script test
